version: '3.9'

services:
  nginx:
    build:
      context: ./_docker/nginx
      dockerfile: nginx.dockerfile
    environment:
      - VIRTUAL_HOST=store.test
      - LETSENCRYPT_HOST=store.test
    # ports:
    #   - 80:80
    volumes:
      - ./:/var/www/html
    depends_on:
    #   - mysql
      - php
  php:

    build:
      context: ./_docker/php
      dockerfile: php.dockerfile

    volumes:
      - ./:/var/www/html
  composer:
    build:
      context: ./_docker/composer
      dockerfile: composer.dockerfile

    volumes:
       - ./src:/var/www/html
    working_dir: /var/www/html
  npm:
    image: node:current-alpine
    volumes:
      - ./:/var/www/html
    entrypoint: ["npm"]
    working_dir: /var/www/html

  artisan:
    build:
      context: ./_docker/php
      dockerfile: php.dockerfile

    volumes:
      - ./:/var/www/html
    # depends_on:
    #   - mysql
    entrypoint: ["php", "/var/www/html/artisan"]

  node_run:
    image: node:current-alpine
    depends_on:
      - nginx
    volumes:
      - ./:/var/www/html
    command: ["npm", "install", "dev", "&&","npm", "run", "dev"]
    working_dir: /var/www/html

networks:
  default:
    name: local
