version: '3.9'

services:
  nginx:
    build:
      context: ./_docker/nginx
      dockerfile: nginx.dockerfile
    environment:
      - VIRTUAL_HOST=store.test
      - LETSENCRYPT_HOST=store.test
    restart: unless-stopped

    # ports:
    #   - 80:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - php

  php:
    build:
      args:
        user: danvop
        uid: 1000
      context: ./_docker/php
      dockerfile: php.dockerfile

    # container_name: travellist-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html




# #   check user privileges
#   npm:
#     image: node:current-alpine
#     volumes:
#       - ./:/var/www/html
#     entrypoint: ["npm"]
#     working_dir: /var/www/html

networks:
  default:
    name: local
